env:
  commonjs: true
  es2021: true
  node: true
  jest: true
extends: airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
rules:
  max-classes-per-file: off
  no-underscore-dangle:
    - error
    - allow:
      - _id
  no-use-before-define:
    - error
    - nofunc
